apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: project-starter-accounts
  namespace: flux-system
spec:
  image: eu.gcr.io/the-mesh-254617/ps-identity-accounts-app-entrypoint
  interval: 1m0s
