apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: accounts
  namespace: istio-system
spec:
  secretName: project-starter-accounts-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'accounts.project-starter.site'
  dnsNames:
    - 'accounts.project-starter.site'
