packageExtensions:
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
  '@graphql-mesh/grpc@*':
    dependencies:
      long: '*'
      protobufjs: '*'
  '@identity/auth-layout-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/error-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/error-page@*':
    dependencies:
      react-helmet: '*'
      react-intl: '*'
  '@identity/index-page@*':
    dependencies:
      react-helmet: '*'
      react-intl: '*'
  '@identity/login-page@*':
    dependencies:
      react-helmet: '*'
      react-intl: '*'
  '@identity/login-password-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/oidc-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/profile-information-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/profile-oidc-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/profile-security-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/profile-sidebar-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/recovery-link-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/recovery-page@*':
    dependencies:
      react-helmet: '*'
      react-intl: '*'
  '@identity/recovery-password-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/registration-page@*':
    dependencies:
      react-helmet: '*'
      react-intl: '*'
  '@identity/registration-password-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/settings-page@*':
    dependencies:
      react-helmet: '*'
      react-intl: '*'
  '@identity/verification-link-fragment@*':
    dependencies:
      react-intl: '*'
  '@identity/verification-page@*':
    dependencies:
      react-helmet: '*'
      react-intl: '*'
  '@monstrs/kratos-session@*':
    dependencies:
      next: '*'
  '@monstrs/react-kratos-forms@*':
    dependencies:
      '@ory/kratos-client': 0.5.5-alpha.4
  '@nestjs/common@*':
    dependencies:
      cache-manager: '*'
      class-transformer: '*'
      class-validator: '*'
      reflect-metadata: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      '@emotion/styled': '*'
      styled-system: '*'
  '@atls-ui-parts/text@*':
    dependencies:
      '@emotion/styled': '*'
      styled-system: '*'
  '@atls-ui-proto/layout@*':
    dependencies:
      react: '*'
  '@atls-ui-proto/text@*':
    dependencies:
      react: '*'
  apollo-server-core@*:
    dependencies:
      graphql: '*'
  apollo-server-express@*:
    peerDependencies:
      graphql: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  fast-json-stringify@*:
    dependencies:
      long: '*'
      uglify-es: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  iconv-lite@*:
    dependencies:
      string_decoder: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220110.hash-b16f567.cjs
