packageExtensions:
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
  '@graphql-mesh/grpc@*':
    dependencies:
      long: '*'
      protobufjs: '*'
  '@monstrs/kratos-session@*':
    dependencies:
      next: '*'
  '@monstrs/react-kratos-forms@*':
    dependencies:
      '@ory/kratos-client': 0.5.5-alpha.4
  '@nestjs/common@*':
    dependencies:
      cache-manager: '*'
      class-transformer: '*'
      class-validator: '*'
      reflect-metadata: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
  '@ui-parts/layout@*':
    dependencies:
      '@emotion/styled': '*'
      styled-system: '*'
  '@ui-parts/text@*':
    dependencies:
      '@emotion/styled': '*'
      styled-system: '*'
  '@atls-ui-proto/layout@*':
    dependencies:
      react: '*'
  '@atls-ui-proto/text@*':
    dependencies:
      react: '*'
  apollo-server-core@*:
    dependencies:
      graphql: '*'
  apollo-server-express@*:
    peerDependencies:
      graphql: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  fast-json-stringify@*:
    dependencies:
      long: '*'
      uglify-es: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  iconv-lite@*:
    dependencies:
      string_decoder: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - .yarn/plugins/@atls/plugin-essentials.cjs

yarnPath: .yarn/releases/yarn-3.1.0-rc.2.cjs
