version: '3.8'

services:
  yarn:
    image: node:16.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - POSTGRESQL_USER=postgres
    ports:
      - 5432:5432

  kratos-proxy:
    image: traefik:v2.6
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - '4433:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  kratos-migrate:
    depends_on:
      - db
    image: docker.io/oryd/kratos:v0.11.0
    environment:
      - DSN=postgres://postgres:password@db:5432/db?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config/ory/kratos
        target: /config/kratos
    command: -c /config/kratos/kratos.yaml migrate sql -e --yes
    restart: on-failure
    networks:
      - default

  kratos:
    depends_on:
      - kratos-migrate
      - mailslurper
      - db
      - kratos-proxy
    image: docker.io/oryd/kratos:v0.11.0
    ports:
      - '4434:4434'
    restart: unless-stopped
    environment:
      - DSN=postgres://postgres:password@db:5432/db?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /config/kratos/kratos.yaml --dev --watch-courier
    networks:
      - default
    volumes:
      - type: bind
        source: ./config/ory/kratos
        target: /config/kratos
    labels:
      - 'traefik.http.services.identity.loadbalancer.server.port=4433'
      - 'traefik.http.routers.identity.rule=Host(`localhost`)'
      - 'traefik.http.routers.identity.middlewares=cors'
      - 'traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=http://localhost:3000'
      - 'traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,OPTIONS'
      - 'traefik.http.middlewares.cors.headers.accesscontrolallowheaders=content-type,authorization,cookie'
      - 'traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true'

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

  oathkeeper:
    image: oryd/oathkeeper:v0.40.1
    command: serve --config /config/oathkeeper/oathkeeper.yml
    volumes:
      - type: bind
        source: ./config/ory/oathkeeper
        target: /config/oathkeeper
    ports:
      - 4455:4455
      - 4456:4456

  identity:
    image: node:16.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @identity/renderer-entrypoint dev
    depends_on:
      - kratos
    ports:
      - '3000:3000'
