version: '3.8'

services:
  yarn:
    image: node:alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - unplugged:/workspace/.yarn/unplugged
    entrypoint: yarn

  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
    ports:
      - 5432:5432

  kratos-migrate:
    depends_on:
      - db
    image: oryd/kratos:v0.7.6-alpha.1
    environment:
      - DSN=postgres://postgres:password@db:5432/db?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: .config/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yaml migrate sql -e --yes
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
      - mailslurper
      - db
    image: oryd/kratos:v0.7.6-alpha.1
    ports:
      - '4433:4433'
      - '4434:4434'
    restart: unless-stopped
    environment:
      - DSN=postgres://postgres:password@db:5432/db?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yaml --dev --watch-courier
    volumes:
      - type: bind
        source: .config/kratos
        target: /etc/config/kratos
    networks:
      default:
        aliases:
          - kratos-public
          - kratos-admin

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

  accounts:
    depends_on:
      - kratos
    image: node:alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - unplugged:/workspace/.yarn/unplugged
    entrypoint: yarn workspace @identity/accounts-app-entrypoint dev
    #environment:
    #  - MQTT_URL=mqtt://mosquitto:1883
    #  - DB_HOST=db
    #depends_on:
    #  - mosquitto
    #  - db
    ports:
      - '3000:3000'

volumes:
  unplugged:
