version: v0.11.0

dsn: memory

serve:
  public:
    base_url: http://localhost:4433/
  admin:
    base_url: http://kratos:4434/

session:
  cookie:
    domain: localhost

selfservice:
  default_browser_return_url: http://localhost:3000/profile/settings
  allowed_return_urls:
    - http://localhost:3000/
    - http://localhost:4434/

  methods:
    password:
      enabled: true
    link:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: project-starter.local
    lookup_secret:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: 164289d994fb493bf23b
            client_secret: 8ed83e4e4919087e9859d74e5622ad7328db872e
            mapper_url: file:///etc/config/kratos/oidc.github.jsonnet
            scope:
              - user:email
          - id: facebook
            provider: facebook
            client_id: '1556094978093786'
            client_secret: 2e322a8a6d4c67f8d146b298a7931a07
            mapper_url: file:///etc/config/kratos/oidc.facebook.jsonnet
            scope:
              - email

  flows:
    error:
      ui_url: http://localhost:3000/auth/error

    settings:
      ui_url: http://localhost:3000/profile/settings
      privileged_session_max_age: 15m
      required_aal: aal1

    recovery:
      enabled: true
      ui_url: http://localhost:3000/profile/recovery

    verification:
      enabled: true
      ui_url: http://localhost:3000/auth/verification
      after:
        default_browser_return_url: http://localhost:3000/

    logout:
      after:
        default_browser_return_url: http://localhost:3000/auth/login

    login:
      ui_url: http://localhost:3000/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:3000/auth/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  schemas:
    - id: default
      url: file:///config/kratos/identity.schema.json
  default_schema_id: default

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true&legacy_ssl=true
