serve:
  proxy:
    cors:
      enabled: true
      allowed_origins:
        - '*'
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - '*'
      exposed_headers:
        - '*'
      allow_credentials: true
      debug: true
    port: 4455

access_rules:
  repositories:
    - file:///rules.json

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true

  mutators:
    header:
      enabled: true
      config:
        headers:
          X-Oathkeeper: oathkeeper

    noop:
      enabled: true

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest

  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: '@this'
      subject_from: 'identity.id'
      only:
        - ory_kratos_session
