---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: project-starter-hydra
  namespace: flux-system
spec:
  chart:
    spec:
      chart: hydra
      sourceRef:
        kind: HelmRepository
        name: ory
      version: 0.5.5
  interval: 1h0m0s
  releaseName: hydra
  targetNamespace: project-starter
  values:
    maester:
      enabled: false

    hydra:
      autoMigrate: true

      config:
        serve:
          public:
            port: 4444
          admin:
            port: 4445
          tls:
            allow_termination_from:
              - 127.0.0.1/32
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16

        urls:
          consent: https://accounts.ps.atls.tech/oauth/consent
          error: https://accounts.ps.atls.tech/oauth/error
          login: https://accounts.ps.atls.tech/oauth/login
          logout: https://accounts.ps.atls.tech/oauth/logout
          post_logout_redirect: https://accounts.ps.atls.tech/auth/logout
          self:
            issuer: https://sso.ps.atls.tech/

        dsn: 'postgres://postgres:password@db-postgresql:5432/project-starter?sslmode=disable&max_conns=20&max_idle_conns=4'

        secrets:
          system: '2e5h6Q8Mqq5zdPjS'
