apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kratos-project-starter
  namespace: istio-system
spec:
  secretName: kratos-project-starter-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'identity.ps.atls.tech'
  dnsNames:
    - 'identity.ps.atls.tech'
