apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-oidc-mappers
  namespace: project-starter
data:
  'oidc.github.jsonnet': |
    local claims = {
      email_verified: false
    } + std.extVar('claims');

    {
      identity: {
        traits: {
          [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
          name: {
            first: "Test",
            last: "Test"
          }
        },
      },
    }
