---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: project-starter-kratos
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kratos
      sourceRef:
        kind: HelmRepository
        name: ory
      version: 0.5.7
  interval: 1h0m0s
  releaseName: project-starter-kratos
  targetNamespace: project-starter
  valuesFrom:
    - kind: Secret
      name: kratos-oidc-providers
  values:
    deployment:
      extraVolumes:
        - name: kratos-oidc-mappers-volume
          configMap:
            name: kratos-oidc-mappers

      extraVolumeMounts:
        - name: kratos-oidc-mappers-volume
          mountPath: /etc/config/mappers
          readOnly: true

    service:
      public:
        port: 4433
      admin:
        port: 4434

    image:
      repository: oryd/kratos
      tag: v0.7.6-alpha.1

    kratos:
      autoMigrate: true

      identitySchemas:
        'identity.default.schema.json': |
          {
            "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "Person",
            "type": "object",
            "properties": {
              "traits": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email",
                    "title": "E-Mail",
                    "minLength": 3,
                    "ory.sh/kratos": {
                      "credentials": {
                        "password": {
                          "identifier": true
                        }
                      },
                      "verification": {
                        "via": "email"
                      },
                      "recovery": {
                        "via": "email"
                      }
                    }
                  },
                  "name": {
                    "type": "object",
                    "required": ["first", "last"],
                    "properties": {
                      "first": {
                        "type": "string",
                        "minLength": 2
                      },
                      "last": {
                        "type": "string",
                        "minLength": 2
                      }
                    }
                  }
                },
                "required": ["email", "name"],
                "additionalProperties": false
              }
            }
          }

      config:
        version: v0.7.6-alpha.1

        log:
          level: debug

        hashers:
          argon2:
            parallelism: 1
            memory: 128MB
            iterations: 2
            salt_length: 16
            key_length: 16

        selfservice:
          default_browser_return_url: https://accounts.ps.atls.tech/

          whitelisted_return_urls:
            - https://accounts.ps.atls.tech/auth/registration/complete
            - https://accounts.ps.atls.tech/auth/verification/complete
            - https://accounts.ps.atls.tech/auth/login/complete
            - https://accounts.ps.atls.tech/
            - https://accounts.ps.atls.tech/profile/settings
            - https://accounts.ps.atls.tech/auth/post-logout
            - https://ps.atls.tech

          flows:
            settings:
              ui_url: https://accounts.ps.atls.tech/profile/settings

            logout:
              after:
                default_browser_return_url: https://accounts.ps.atls.tech/auth/login

            registration:
              ui_url: https://accounts.ps.atls.tech/auth/registration
              after:
                password:
                  hooks:
                    - hook: session

            verification:
              enabled: true
              ui_url: https://accounts.ps.atls.tech/auth/verification

            login:
              ui_url: https://accounts.ps.atls.tech/auth/login

            recovery:
              enabled: true
              ui_url: https://accounts.ps.atls.tech/auth/recovery

            error:
              ui_url: https://accounts.ps.atls.tech/auth/error

          methods:
            link:
              enabled: true
            password:
              enabled: true
            profile:
              enabled: true
            oidc:
              enabled: true

        secrets:
          default:
            - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
          cookie:
            - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

        serve:
          public:
            base_url: https://identity.ps.atls.tech/
            cors:
              enabled: true
              allowed_origins:
                - https://accounts.ps.atls.tech

        session:
          cookie:
            domain: .ps.atls.tech

        identity:
          default_schema_url: file:///etc/config/identity.default.schema.json

        courier:
          smtp:
            connection_uri: smtps://AKIA2WVG45RELJFUE37P:BMIC00QbNKtidPxNZXdL2TpTcypMJ5eTTAY2zqGF7Fmy@email-smtp.eu-central-1.amazonaws.com:465/?skip_ssl_verify=true
            from_address: no-reply@atls.tech

        dsn: 'postgres://postgres:password@db-postgresql:5432/project-starter?sslmode=disable'
