apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: project-starter-site
  namespace: flux-system
spec:
  image: eu.gcr.io/the-mesh-254617/ps-site-renderer
  interval: 1m0s
