apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: accounts-app
  namespace: istio-system
spec:
  secretName: project-starter-accounts-app-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'accounts.ps.atls.tech'
  dnsNames:
    - 'accounts.ps.atls.tech'
