apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: project-starter-accounts-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: project-starter-accounts-app
  filterTags:
    pattern: '^[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
